language: objective-c  #1
osx_image: xcode7 #2
xcode_project: Testable2.xcodeproj #3
xcode_scheme: Testable2 #4
xcode_sdk: iphonesimulator #5
#bundler_args: --without development documentation --deployment --jobs=3 --retry=3
#after_success: bundle exec slather
#cache: bundler
#sudo: false