#Uncomment the three lines below if you get xctool version errors on build
#before_install:
#  - brew update
#  - brew upgrade xctool
language: objective-c  #1
osx_image: xcode7 #2
xcode_project: Testable2.xcodeproj #3
xcode_scheme: Testable2 #4
xcode_sdk: iphonesimulator #5